services:
  mcnotes:
    image: ghcr.io/lmcnatt/mcnotes:latest
    container_name: mcnotes
    restart: unless-stopped
    ports:
      - "3010:3010"
    volumes:
      - mcnotes-data:/data

volumes:
  mcnotes-data:
